// users
export const CREATE_USER = 'CREATE_USER';
// wallet
export const GET_WALLET_USER_ID = 'GET_WALLET_USER_ID';
export const REQUEST_STARTED = 'REQUEST_STARTED';
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const GET_CURRENCIES = 'GET_CURRENCIES';
export const SAVE_NEW_EXPENSE = 'SAVE_NEW_EXPENSE';
export const GET_ID_TO_EDIT = 'GET_ID_TO_EDIT';
export const SAVE_EDITED_EXPENSE = 'SAVE_EDITED_EXPENSE';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
