// users
export const CREATE_USER = 'CREATE_USER';
export const EDIT_USER = 'EDIT_USER';
export const DELETE_USER = 'DELETE_USER';
// wallet
export const WALLET_REQUEST_STARTED = 'REQUEST_STARTED';
export const WALLET_REQUEST_FAILED = 'REQUEST_FAILED';
export const GET_WALLET_USER_ID = 'GET_WALLET_USER_ID';
export const GET_WALLET_CURRENCIES = 'GET_WALLET_CURRENCIES';
export const SAVE_NEW_EXPENSE = 'SAVE_NEW_EXPENSE';
export const GET_EXPENSE_ID_TO_EDIT = 'GET_EXPENSE_ID_TO_EDIT';
export const SAVE_EDITED_EXPENSE = 'SAVE_EDITED_EXPENSE';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
export const SHOW_EXPENSE_FORM = 'SHOW_EXPENSE_FORM';
